server:
  port: 8099
eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: shop-cart-api
sku:
 count:
  limit: 10